name: hiper
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - pip:
    - accelerate==0.12.0
    - bitsandbytes==0.35.4
    - diffusers==0.9.0
    - opencv-python==4.7.0.72
    - tokenizers==0.13.2
    - tqdm==4.64.1
    - transformers==4.25.1
